services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: istalearning
    volumes:
      - ./backend/sql/init_data.sql:/docker-entrypoint-initdb.d/01_init_data.sql
      - ./backend/sql/fake_data.sql:/docker-entrypoint-initdb.d/02_fake_data.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: istalearning
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "3000:3000"